.TH "Code/libGPS.py" 3 "Version 3.0" "DE2-Project-GPS-Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Code/libGPS.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMicropyGPS\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBlibGPS\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DE2-Project-GPS-Tracker from the source code\&.
