.TH "Code/Main_v2.0.py" 3 "Version 3.0" "DE2-Project-GPS-Tracker" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Code/Main_v2.0.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMain_v2\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBinitialize_display\fP ()"
.br
.ti -1c
.RI "\fBupdate_display\fP (oled, gps_data)"
.br
.ti -1c
.RI "\fBparse_gps_data\fP (my_gps)"
.br
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBI2C_SCL_PIN\fP = 22"
.br
.ti -1c
.RI "int \fBI2C_SDA_PIN\fP = 21"
.br
.ti -1c
.RI "int \fBI2C_FREQ\fP = 100_000"
.br
.ti -1c
.RI "int \fBUART_TX_PIN\fP = 17"
.br
.ti -1c
.RI "int \fBUART_RX_PIN\fP = 16"
.br
.ti -1c
.RI "int \fBUART_BAUDRATE\fP = 9600"
.br
.ti -1c
.RI "int \fBOLED_CONTRAST\fP = 80"
.br
.ti -1c
.RI "int \fBDISPLAY_REFRESH_INTERVAL\fP = 1"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DE2-Project-GPS-Tracker from the source code\&.
