.TH "Code/sh1106.py" 3 "Version 4.0" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Code/sh1106.py
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSH1106_I2C\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsh1106\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBi2c\fP = I2C(0, scl=Pin(22), sda=Pin(21), freq=400_000)"
.br
.ti -1c
.RI "\fBoled\fP = \fBSH1106_I2C\fP(\fBi2c\fP)"
.br
.ti -1c
.RI "list \fBicon\fP"
.br
.ti -1c
.RI "\fBpos_x\fP"
.br
.ti -1c
.RI "\fBpos_y\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
